default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fakebook_app_development
  
test:
  <<: *default
  database: fakebook_app_test
  
production:
  <<: *default
  database: fakebook_app_production
  username: fakebook_app
  password: <%= ENV['FAKEBOOK_APP_DATABASE_PASSWORD'] %>
